plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.gnotesamsung7hue.shadowgrid'
    compileSdk 34

    defaultConfig {
        applicationId 'io.github.gnotesamsung7hue.shadowgrid'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '0.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
